### PR TITLE
Fix relative path loading.

### LINKED ISSUE #224: Path to ca.pem must be absolute
```
Error: ENOENT: no such file or directory, open 'mycluster/ca.pem'
Logger.js:133
	at Object.fs.openSync (fs.js:577:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:483:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:563:29)
	at bufferFromFileOrString (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:280:19)
	at KubeConfig.applyHTTPSOptions (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:199:38)
	at KubeConfig.applyOptions (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:234:14)
	at KubeConfig.applyToRequest (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:77:14)
	at Extensions_v1beta1Api.listIngressForAllNamespaces 
[...]
```

My cluster config contains
```
- cluster:
    certificate-authority: mycluster/ca.pem
```

If I replace that path `mycluster/ca.pem` with an absolute path (`/Users/tim/.kube/mycluster/ca.pem`), then it works.
If the path is a relative one, or if the file is not found, perhaps the library could prepend the kube config directory `$HOME/.kube/` to the configured path?

FWIW the relative path config worked out-of-the-box with the godaddy `kubernetes-client`, but I like this library's API and typings much more, so I'd like to switch over!

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #224

### CODE REVIEW

**Comment by drubin** [comment]
@brendanburns I was going to ask about if this makes sense or if we should load the path relative to the proccess working directory. 

BUT I see yet again the k8s docs/spec is so well documented https://github.com/kubernetes/kubernetes/pull/20328/files 

You need to fix the linting but then I think it should be good to go.

**Comment by brendandburns** [comment]
@drubin lint fixed, I think this is ready to go.

Thanks!

**Comment by starpit** [comment]
for future reference: this fix does not work for configs loaded directly from string, a fallback which is required for users that have a colon-separated KUBECONFIG (which is also not supported by loadConfigFromDefault())

**Comment by drubin** [comment]
@starpit I added an issue to add this functionality into the client, See above.

**Pull request merged**
