### PR TITLE
Update to version 0.14.4

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by drubin** [comment]
Needs a rebase and then I will re-review

**Comment by brendandburns** [comment]
@drubin sorry this dropped. Rebased, please take another look!

Thanks!

**Comment by drubin** [comment]
Please also change the title of the MR to match the version `0.14.4` if I add my lgtm its going to merge this and it will be confusing in the history

**Comment by brendandburns** [comment]
@drubin fixed, thanks.

**Pull request merged**
