### PR TITLE
Fixes property name in V1beta1CustomResourceColumnDefinition

### PR DESCRIPTION
**Pull request by trebler**
Fixes issue with deploying, e.g. cert-manager (https://github.com/jetstack/cert-manager/releases/download/v0.9.0/cert-manager.yaml)

"JSONPath" starts with capital "J" (ref. https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/types.go#L204)

### CODE REVIEW

**Comment by brendandburns** [comment]
@trebler did you regenerate the code or hand edit this?

Please see:
https://github.com/kubernetes-client/javascript/issues/305

We need to re-generate the code with these fixes and the open api generator.

**Comment by brendandburns** [comment]
Instructions for regenerating are here:
https://github.com/kubernetes-client/javascript#re-generating-code

**Comment by trebler** [comment]
I will create a new PR with openapi-generator recompiled api

**Pull request closed without merging**
