### PR TITLE
Upgrade to 1.13 API with fixes

### PR DESCRIPTION
**Pull request by brendandburns**
@flyboarder 

This is #173 with an added commit to fix CI/CD.

@flyboarder probably the right thing to do is to cherry-pick my commit onto your PR and then merge your PR (and then we can close this PR)

Alternately, we could merge this PR instead.

### CODE REVIEW

**Comment by flyboarder** [comment]
@brendandburns we can just merge this one, if it fixes the problems then great let's get it into master. My questions: Do we need to run any additional steps in the future to regenerate this package? How did you fix it? Can we include those steps within a build script?

**Comment by brendandburns** [comment]
@flyboarder I hand edited the generated code. This isn't sustainable, we need a fix in the code generator, but we're likely to switch the code generator before we regenerate again...

**Comment by brendandburns** [comment]
@drubin @itowlson can I get a quick review here?

Thanks!

**Comment by flyboarder** [comment]
@brendandburns where is the work for switching the code generator? I'd like to get in on that!

**Pull request merged**
