### PR TITLE
add NetworkingV1 Ingress example

### PR DESCRIPTION
**Pull request by vBitza**
Hi,

I recently needed to add a Ingress on the newer "networking.k8s.io/v1" since the example you have is on "networking.k8s.io/v1beta" I decided to add my work here aswell. I've also renamed the first example you had to properly differentiate the two files based on apiVersion.

Have a nice day!

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the PR, we need to have you sign the CLA.

Also, since the v1beta1 Ingress API is deprecated, I think you can just modify the existing ingress example to use `v1` instead of `v1beta1`

Thanks!

**Comment by vBitza** [comment]
CLA signed and PR updated as per request.

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
