### PR TITLE
Update to openapi-generator

### PR DESCRIPTION
**Pull request by silasbw**
```
USERNAME=kubernetes ../gen/openapi/typescript.sh src/gen settings
```

### CODE REVIEW

**Comment by silasbw** [comment]
* Linter, prettier, coverage, and gen settings for openapi-generator: https://github.com/kubernetes-client/javascript/pull/307/commits/e83d9def090a1111b8af3cecf618650834957736
* New generated code: https://github.com/kubernetes-client/javascript/pull/307/commits/320d5427a63a47aefe949aae5d44dd6e22e1c30a

**Comment by silasbw** [comment]
/assign @mbohlool
cc @brendandburns and @drubin

**Comment by brendandburns** [comment]
LGTM. @drubin do you have strong feelings about `gen` vs `lib`?

**Comment by silasbw** [comment]
Do you have cycles to chime in on https://github.com/kubernetes-client/gen/pull/125 @brendandburns ?

**Comment by drubin** [comment]
No strong feelings on lib vs gen just want to make it clear it's not hand crafted. 

but I feel like we should merge the upstream changes before this one.

**Comment by brendandburns** [comment]
https://github.com/kubernetes-client/gen/pull/125 has now merged

/lgtm
/approve

**Pull request merged**
