### PR TITLE
generated code migration from request to node-fetch/isomorphic-fetch

### PR DESCRIPTION
**Pull request by davidgamero**
migration of OpenAPIGenerator code to current typescript generator that no longer uses `request`
in reference to #754

Note: this will leave the master branch in a development state as the migration doesn't cover the /src/*.ts files that still use request.
Merging this would allow the work of updating all the non-generated code to be parallelized on master.

Notable remaining migration work:
-watch.ts, log.ts, and metrics.ts all directly implement `request` without using the generated apiclient
-config.ts needs to be refactored from the `applyToRequest()` method to the new `applySecurityAuthentication()` method now that the generated code uses a `SecurityAuthentication` interface for creating a `RequestContext` instead of directly passing `https.Options`

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks!

Can you split this PR into two commits: 1) generated code changes. 2) any hand-edited changes.

It's basically impossible to review the generated code because there are so many files, but I would like to review any hand-edited changes.

Also you need to sign the CLA. Just do the EasyCLA one b/c there is migration happening to that today-ish.

**Comment by davidgamero** [comment]
The only hand-edited change in this PR is the GEN_COMMIT hash, and I will be making a separate PR for the hand-edited changes after this one for converting the `config` to the new interfaces.
Should I do the GEN_COMMIT hash change in a separate commit from the code generated by altering it for clarity?

Sounds good I'll do the CLA

**Comment by brendandburns** [comment]
@davidgamero I created a `release-1.x` repo. Let's move this PR to target that repo and we can merge and iterate.

**Comment by davidgamero** [comment]
perfect. just retargeted the PR

**Comment by davidgamero** [comment]
looks like the PR might need a rebase- I could just open a new one at this point

**Pull request closed without merging**
