### PR TITLE
move @types/ws to a runtime dependency

### PR DESCRIPTION
**Pull request by sroylance**
I believe this will fix a warning I'm getting:
node_modules/@kubernetes/client-node/dist/exec.d.ts:2:23 - error TS2688: Cannot find type definition file for 'ws'.

2 /// <reference types="ws" />

### CODE REVIEW

**Comment by itowlson** [comment]
Looks good and would be great to fix this annoyance!  When you say you believe this will fix the warning, have you been able to test this, or does it need to go through a packaging step to test that it fixes the warning?

**Comment by sroylance** [comment]
it needs to be tested, I haven't tried to build it.  Adding @types/ws to the package.json in the application I'm working on solved the problem for me.

**Comment by drubin** [comment]
@sroylance Thanks for this! 

I think #202 covers your usecase as well as fixing a few others. Are you ok if we close this in favour of that?

**Comment by drubin** [comment]
/close

#202 was merged

Let me know if there are still outstanding issues.

**Pull request closed without merging**
