### PR TITLE
docs: hosts autogenerated docs on GitHub Pages via Actions, updates README

### PR DESCRIPTION
**Pull request by mattxwang**
Hi! This is a relatively small PR that addresses #697. It does two things:

1. consumes [`JamesIves/github-deploy-action`](https://github.com/JamesIves/github-pages-deploy-action) to push the output of `npm run docs` to the `gh-pages` branch, only on push to `master`
2. updates the README with relevant links and information (badge, hosted docs, and the K8s API reference discussed in the issue)

On top of merging this PR in, we would also need to manually enable pages, which can be done in Settings > Pages > Source > "gh-pages" (with `/` as the root). That would deploy the site to https://kubernetes-client.github.io/javascript/

You can test my changes in the fork at https://mattxwang.github.io/javascript/ 

Let me know if there's anything else I should add/remove to this PR!

(as a follow up, I think it might be helpful to include the relevant versions for the docs somewhere on the site; that likely warrants a follow-up PR)

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Comment by mattxwang** [comment]
Thanks @brendanburns! I think there's one more step that we need to do, and I can't do it to this repository without admin privileges:

> On top of merging this PR in, we would also need to manually enable pages, which can be done in Settings > Pages > Source > "gh-pages" (with / as the root). That would deploy the site to https://kubernetes-client.github.io/javascript/

If you'd like, we could also add the link to the repository info.

**Comment by mattxwang** [comment]
Thanks @brendandburns! I think there's one more step that we need to do, and I can't do it to this repository without admin privileges:

> On top of merging this PR in, we would also need to manually enable pages, which can be done in Settings > Pages > Source > "gh-pages" (with / as the root). That would deploy the site to https://kubernetes-client.github.io/javascript/

If you'd like, we could also add the link to the repository info section.

**Comment by brendandburns** [comment]
This is now done.

https://kubernetes-client.github.io/javascript/

If there are additional PRs to add links to the README feel free to send them along.

Thanks!

**Comment by mattxwang** [comment]
Hi @brendandburns, I'm not sure if the GitHub pages host is pointing to the right branch - https://kubernetes-client.github.io/javascript/ looks like it's just hosting the README currently, while https://mattxwang.github.io/javascript/ has the rest of the Typedoc UI (i.e. search bar, classes on the right, etc.) - would you be able to check that GitHub Pages is pointed at `gh-pages` when you have a chance?

**Pull request merged**
