### PR TITLE
Fix for running in electron environment

### PR DESCRIPTION
**Pull request by mkramb**
I'm using `kubernetes-client` in `electron` environment (in main/node renderer) and the underlying library `shelljs` has issues when running as an electron package application. More information here:
- https://github.com/shelljs/shelljs/issues/480
- https://github.com/shelljs/shelljs/wiki/Electron-compatibility

Based on testing the cleanest solution is setting exec to async mode, which doesn't have this problem. I'm using this in https://github.com/mkramb/jx-tray which is a start of https://jenkins-x.io desktop client.

No changes in functionality & existing tests are passing.

### CODE REVIEW

**Comment by brendandburns** [comment]
@mkramb we need you to sign the CNCF CLA.

Thanks!

**Comment by brendandburns** [comment]
@mkramb does this actually work? This is changing the call from being synchronous to being asynchronous and I worry that there is a race between token update and web request generation...

(separately I'm having similar issues for the Azure provider, so we do need to deal with async clients somehow here...)

**Comment by mkramb** [comment]
I have signed CLA.

It works (tested in electron environment) and also existing tests are passing, also the attached issue - if you look at the last comment from the ShellJS maintainer, it looks like best solution ATM.

https://github.com/shelljs/shelljs/issues/480

**Comment by brendandburns** [comment]
This needs a rebase.

I still am not confident that this will work correctly given that it is switching the call from sync to async, it feels racy to me... (and I'm not positive the tests cover that particular part of the code, sorry!)

Any chance that you can conditionalize this so that it only works this way when running in electron?

Thanks!

**Comment by itowlson** [comment]
Would a safe way forward on this be to create `async` versions of the `applyToHTTPSOptions` and `applyToRequest` functions, and call the async version of `shelljs.exec` only from within those async forms?  Then Electron apps could call the `applyToHTTPSOptionsAsync` and `applyToRequestAsync` methods, while vanilla Node applications could call either the sync or async methods.

Most places within the code that call `applyToHTTPSOptions` or `applyToRequest` seem to be returning Promises, so could call the async versions.

It would be a much larger piece of work though (and not lacking in risk either).

**Comment by edvald** [comment]
This doesn't actually work, it just swallows the error because the function returns immediately, and doesn't have an error event handler. I would suggest switching from `shelljs` to https://github.com/sindresorhus/execa instead (and making the enclosing function async along the way), since none of the other features of shelljs are being used. I can make a quick PR for that if you'd like.

**Pull request closed without merging**
