### PR TITLE
Fix proxy tests

### PR DESCRIPTION
**Pull request by krmodelski**
Fix proxy tests added in [this](https://github.com/kubernetes-client/javascript/pull/2111) PR.

### CODE REVIEW

**Comment by krmodelski** [comment]
@cjihrig should I create PR for main or release-1.x?

**Comment by cjihrig** [comment]
Please target main.

**Comment by cjihrig** [comment]
I don't appear to have permission to trigger the CI yet.

**Review by anandfresh — APPROVED** [review]

**Comment by brendandburns** [comment]
@cjihrig I don't think `/ok-to-test` works for tests that use github actions instead of prow.  There's a button down in the "review requested" section which enables testing.

If you can't see that button we probably need to add you in the repo settings somewhere.

**Comment by cjihrig** [comment]
Yea, I have seen that button in other repos. I think the issue is that I am a member of the kubernetes-client org, but don't have any actual permissions in this repo.

**Pull request merged**
