### PR TITLE
Makes "unexpected event" error message more useful

### LINKED ISSUE #108: Watch.watch(...) throws error with useless [object Object]
I got the following when running my code:
```
/home/node/app/node_modules/@kubernetes/client-node/dist/watch.js:35
                throw new Error(`unexpected object: ${obj}`);
                ^

Error: unexpected object: [object Object]
    at LineStream.stream.on (/home/node/app/node_modules/@kubernetes/client-node/dist/watch.js:35:23)
    at LineStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at LineStream.Readable.push (_stream_readable.js:219:10)
    at LineStream.Transform.push (_stream_transform.js:151:32)
    at LineStream._pushBuffer (/home/node/app/node_modules/byline/lib/byline.js:126:17)
    at LineStream._transform (/home/node/app/node_modules/byline/lib/byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:190:10)
    at LineStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at LineStream.Writable.write (_stream_writable.js:294:11)
    at Request.ondata (internal/streams/legacy.js:15:31)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/home/node/app/node_modules/request/request.js:1080:12)
```
The `[object Object]` doesn't tell me much, and i guess it's not suppose to be this way.

This happens because the object is added to the error as a string. Using something like `JSON.stringify` on  `obj` before adding it to the error would make it useful.

### PR DESCRIPTION
**Pull request by VegarM**
Fixes #108

### CODE REVIEW

**Comment by brendandburns** [comment]
@VegarM looks good to me but we need you to sign the CNCF CLA...

**Comment by VegarM** [comment]
I didn't get the email agreement to sign.
Have contacted the linux foundation about this.

It seems like they're having problems sending out emails atm.
image

Guess I'll have to wait.

**Comment by brendandburns** [comment]
Someone seems to have signed it successfully recently. Try again?

I'd love to merge this.

thanks

**Comment by brendandburns** [comment]
@VegarM Friendly ping on this one.

Thanks!

**Comment by VegarM** [comment]
No reply from cncf

**Comment by VegarM** [comment]
Agreement signed

**Comment by itowlson** [comment]
/lgtm

And thanks for battling through the CNCF stuff!

**Pull request merged**
