### PR TITLE
Watch with labelSelector

### PR DESCRIPTION
**Pull request by StefanCenusa**
Implements #644 

Adds the possibility to add a labelSelector to both Informer and ListWatch such that events that are generated after the initial list function are filtered by that selector.

### CODE REVIEW

**Comment by brendandburns** [comment]
This looks good to me. I have two requests before we can merge:

1) You need to sign the CNCF CLA
2) Please add a unit test to validate this behavior.

Thanks again!

**Comment by StefanCenusa** [comment]
1. I will sign the CNCF CLA asap but I am waiting on a support ticket on LinuxFoundation to fix my account first.
2. I am not sure how I can test that the server will return an event with the correct labels. I mean the labelSelector feature is implemented server side.

**Comment by brendandburns** [comment]
@StefanCenusa for the test, it is sufficient to mock the server and just validate that the right label selector is sent as a query parameter.

**Comment by StefanCenusa** [comment]
@brendanburns I've added a test case

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for adding the test!

**Comment by brendandburns** [comment]
oops, looks like you may need to run `npm run format` to fix formatting errors.

`npm run lint` should validate that it looks clean.

Thanks

**Comment by StefanCenusa** [comment]
@brendanburns I think I did it right this time

**Comment by StefanCenusa** [comment]
@brendandburns when will be the next realease?

**Pull request merged**
