### PR TITLE
Move @types to package.json dependencies for definitions and add missing @types

### PR DESCRIPTION
**Pull request by sheldonkwok**
We need the module's dependency's types in the `dependencies` part of the package.json for typescript to see them. More reasoning can be found here: https://github.com/Microsoft/types-publisher/issues/81

### CODE REVIEW

**Comment by sheldonkwok** [comment]
I just signed up for the CNCF CLA but I'm not sure how to retrigger w/o another commit.

**Comment by sheldonkwok** [comment]
Adding the @types to the dependencies itself didn't work. I ended up having to add new @types and change code.

**Comment by sheldonkwok** [comment]
Closes #37

**Comment by brendandburns** [comment]
LGTM, thanks.

**Pull request merged**
