### PR TITLE
Remove underscore js

### PR DESCRIPTION
**Pull request by DavidIsa**
This pull request proposes the removal of the Underscore.js library from the project. After careful consideration and evaluation of the project's requirements, it has been determined that removing underscore.js will bring several benefits.
Underscore js is an external dependency that needs to be maintained and updated alongside the project. By removing the library, we reduce the number of dependencies we need to manage, simplify the maintenance process, and potentially avoid compatibility issues or security vulnerabilities. Including Underscore.js in the project adds unnecessary file size and overhead, as it introduces an extra dependency that needs to be loaded by the application. Removing Underscore.js will help reduce the overall size of the project and potentially improve performance, particularly if a significant portion of its features is not utilized.

### CODE REVIEW

**Review by mstruebing — APPROVED** [review]
Thank you, removing deps is always a good idea I think and in this case we use the features of underscore very little.

**Comment by brendandburns** [comment]
Thanks for the PR. It looks like tests are failing. You can run the tests with `npm run test`

**Comment by DavidIsa** [comment]
Thanks for the PR review!

I've pushed a new commit with the fix

**Comment by brendandburns** [comment]
Sorry, looks like formatting failed now :(

You can run `npm run format` and `npm run lint`

Thanks!

**Comment by mstruebing** [comment]
Could you still run `npm run format` and commit the changes?

**Comment by DavidIsa** [comment]
Done

**Pull request merged**
