### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by silasbw**
Broken by API change in https://github.com/kubernetes-client/javascript/pull/268

### CODE REVIEW

**Comment by brendandburns** [comment]
I have mixed feelings about merging this, since this `README.md` ends up in the `npm` page, where these examples still are correct, and yet they are broken at head...

How do you think we should handle this (other than obviously cutting the 0.10.0 release :)

**Comment by drubin** [comment]
>I have mixed feelings about merging this, since this README.md ends up in the npm page, where these examples still are correct, and yet they are broken at head... 

@brendandburns  The readme that is displayed on the NPm page is actually packaged into the NPM package when you release it.  https://github.com/kubernetes-client/javascript/commit/32fa2902c9d74f40bf56762a41344bd522caefd0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L12

**Pull request merged**
