### PR TITLE
Update to Kubernetes API Version 1.18

### PR DESCRIPTION
**Pull request by tux-rampage**
The OpenAPI-Spec this library was generated for is outdated (v1.15)
This PR aims to provide updated API objects for the current stable release (1.18)

### CODE REVIEW

**Comment by tux-rampage** [comment]
This should fix #438

**Comment by brendandburns** [comment]
Thanks for doing this. Can you split this into two commits:

* Commit #1: generated code
* Commit #2: manual changes

**Comment by tux-rampage** [comment]
Yes. I can do that tomorrow.

**Comment by tux-rampage** [comment]
@brendanburns I've splitted the commit into three commits:

1. Changes to the api gen config
2. Re-generated API code
3. Manual changes

I hope this helps

**Comment by brendandburns** [comment]
thanks, it makes it much easier to review.

/lgtm
/approve

**Pull request merged**
