### PR TITLE
Add the ability to push a non pre-release to NPM

### PR DESCRIPTION
**Pull request by brendandburns**
Final piece needed to cut the 1.0.0 release, I think.

### CODE REVIEW

**Comment by brendandburns** [comment]
cc @cjihrig @mstruebing

**Comment by brendandburns** [comment]
Hrm, looks like some prettier thing reformatted the YAML file, so it looks all changed. Let me know if you want me to revert the whitespace changes.

**Comment by cjihrig** [comment]
Viewing the diff with `?w=1` added to the end of the URL takes care of that problem.

**Pull request merged**
