### PR TITLE
regenerate for 1.13.2

### PR DESCRIPTION
**Pull request by flyboarder**
regenerate the api for k8s version 1.13.2

### CODE REVIEW

**Comment by flyboarder** [comment]
@brendandburns this needs the same fix as #126

**Comment by brendandburns** [comment]
@flyboarder thanks for doing this, are you planning to get CI clean or do we need a different PR to merge.

**Comment by flyboarder** [comment]
@brendandburns Im not sure what this needs to get merged, could you try on your end? Im using master to regenerate this.

**Comment by brendandburns** [comment]
ok, I'll try to get CI/CD passing with this PR.

**Pull request merged**
