### PR TITLE
Fix expires-on case on Azure auth

### PR DESCRIPTION
**Pull request by laudibert**
Fix for #752

### CODE REVIEW

**Comment by laudibert** [comment]
I signed it

**Comment by brendandburns** [comment]
Thanks for the PR!

\lgtm
\approve

**Comment by laudibert** [comment]
Ah, sorry for the format error. Fixed now.

**Comment by brendandburns** [comment]
\lgtm
\approve

**Comment by laudibert** [comment]
Thanks @brendandburns , is there anything I can do to make a 0.16.2 be released with that PR included?

**Pull request merged**
