### PR TITLE
Update version-check.js

### PR DESCRIPTION
**Pull request by Himanshu-holmes**
I have added console.log function to check the function is working .

### CODE REVIEW

**Comment by brendandburns** [comment]
Can you comment on the usecase where this is necessary? I'm not sure that it is required.

**Comment by Himanshu-holmes** [comment]
@brendandburns Yes you are right, I was just trying to contribute but since this is not important so you can ignore it.

**Comment by brendandburns** [comment]
@Himanshu-holmes thanks for the interest in the project. If you are interested in contributing further, there is a list of good first issues:

https://github.com/kubernetes-client/javascript/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Thanks!

**Pull request closed without merging**
