### PR TITLE
Fix exec.

### LINKED ISSUE #216: Authentification
Hi , 
I'm wondering if there is any way to make an authentification ? or if the error is related to something else ? 

`'pods is forbidden: User "system:anonymous" cannot list pods in the namespace "default"',`

I was trying the exemple to get pods from default namespace but I'm stuck with this error

The kubernetes cluster is on AWS.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #216

### CODE REVIEW

**Comment by drubin** [comment]
@brendanburns My biggest concern is that the test coverage doesn't feel enough for all the defensive checks that were added?

But other wise the good looks good.

**Comment by brendandburns** [comment]
@drubin actually, I had a bug in some of the defensive stuff and it lit the tests up pretty good :)

**Comment by brendandburns** [comment]
But I'm happy to add further tests specific to that code if you'd prefer.

**Comment by drubin** [comment]
/lgtm

@brendanburns It was just a feeling but I didn't look at the rest of the existing tests so happy to defer to your judgement here.

**Pull request merged**
