### PR TITLE
Rev version to 0.8.2 now that 0.8.1 is published.

### PR DESCRIPTION
**Pull request by brendandburns**
@itowlson @drubin

### CODE REVIEW

**Comment by itowlson** [comment]
Should we regenerate `package-lock.json` to match before merging?

**Comment by drubin** [comment]
> Should we regenerate `package-lock.json` to match before merging? 

Yes, we should. I added a "test" for this but I didn't take into account CI first runs `npm ci` which updates the `package-lock.json` will add a basic test before we run `npm ci`

**Comment by drubin** [comment]
@brendanburns Also any chance we can make it part of the release process to also add a github release? many people subscribe to only releases so they can be notified when we publish new releases?

I noticed we haven't published a release since 0.7.0 https://github.com/kubernetes-client/javascript/releases

**Comment by brendandburns** [comment]
@drubin Yeah, that's a good point. I filed https://github.com/kubernetes-client/javascript/issues/208 to track this.

**Comment by drubin** [comment]
Thanks @brendandburns

**Comment by brendandburns** [comment]
@drubin I sent #210 to improve things. Any chance we can merge this PR?

Thanks!

**Comment by drubin** [comment]
@brendandburns the package-lock.json still needs to be updated(else every time you npm install you will get a dirty tree) .

If you set that also to 0.8.2 it should be good to merge.

**Comment by brendandburns** [comment]
oops, good reminder. Fixed.

**Comment by brendandburns** [comment]
@drubin is there a way for us to extend our CI/CD so that it would fail in situations like this?

**Comment by drubin** [comment]
/lgtm

Will submit a pr when I get a second just kinsa busy this week end

**Pull request merged**
