### PR TITLE
fix(websockethandler): fix buffer init in handleStandardInput

### PR DESCRIPTION
**Pull request by cmosgh**

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the contribution, we need a signed CLA.

Thanks!

**Comment by cmosgh** [comment]
@brendanburns can you merge this and somehow make it available for npm install 😄  ?

**Comment by brendandburns** [comment]
Thanks for the CLA, merged and will cut a new release today...

**Comment by brendandburns** [comment]
@cmosgh published as 0.5.0 looks like it takes a while to become public but it should be there once npm.org catches up....

**Pull request merged**
