### PR TITLE
Switch to the typescript generated client.

### PR DESCRIPTION
**Pull request by brendandburns**
* Add examples for how to use typescript from javascript.
   * Update documentation.
   * Add in the typescript client from https://github.com/kubernetes-client/typescript

Will deprecate the typescript repository once this is merged.

### CODE REVIEW

**Comment by brendandburns** [comment]
@mbohlool

**Comment by mbohlool** [comment]
@brendandburns I would be fine with this solution. Another approach we can take is to rename typescript client to javascript and have typescript and javascript examples there. Typescript would be the language we use to implement javascript client. I like this approach more. WDYT?

**Comment by brendandburns** [comment]
That's fine with me too, I will do that PR.

Thanks
--brendan



________________________________________

**Comment by brendandburns** [comment]
Ok, PR updated to add in the typescript client here.

I will deprecate the typescript-only repo once this PR is merged.

**Comment by brendandburns** [comment]
@mbohlool friendly monday morning ping (assuming you're not on vacation... If you are, please ignore :)

**Comment by mbohlool** [comment]
LGTM.

**Pull request merged**
