### PR TITLE
fix: wrong targetPort type preventing service api calls

### PR DESCRIPTION
**Pull request by jhkimac**

### CODE REVIEW

**Comment by drubin** [comment]
Hi, @jhkimac Thanks so much for this contribution! 

Sadly we can't accept this as is, as this code is automatically generated from the openApi spec. So we need to fix it upstream in the generator or in the openApi spec. 

See  https://github.com/kubernetes-client/javascript#re-generating-code which calls https://github.com/kubernetes-client/javascript/blob/master/generate-client.sh

How does this fix it compared to the `object` value?

/assign @drubin

**Comment by jhkimac** [comment]
Hi @drubin, I will try it out after a take a bit of rest. In the meantime, I have also found similar behavior in V1Container's `V1Container.livenessProbe.httpGet.port`, type enforcing object instead of number. I cannot find this problem in the openApi spec (or I am just too sleepy) at the moment. Will update after tomorrow.

**Comment by brendandburns** [comment]
This is discussed in #349 there's something weird going on with the Swagger and the code generator. It has to do with the way that IntOrString is represented in Swagger, and also what looks like it might be a bug in the code generator.

I've take a few attempts at fixing this, but it hasn't gone anywhere.

As @drubin says, we can't manually edit the code generated files.

**Comment by brendandburns** [comment]
Closing this PR since we can't merge it. Please continue discussion as needed in #349

**Pull request closed without merging**
