### PR TITLE
split cloud_auth into gcp and azure

### PR DESCRIPTION
**Pull request by mansona**
This PR is to track work on https://github.com/kubernetes-client/javascript/issues/700

This is probably going to be **very** WIP for a long time because I don't really know what I'm doing with this repo 😂  Please be as harsh as possible and tell me what I need to change to move forward 🙇

### CODE REVIEW

**Comment by mansona** [comment]
I've signed the CLA

**Comment by brendandburns** [comment]
@mansona this looks totally reasonable. Please use the tests from `config_test.ts` instead of the ones from oidc and I think that this is good to merge.

**Comment by mansona** [comment]
@brendanburns I pulled the config tests that you mentioned but I only applied them to the azure file since they were all azure. Do you want me to duplicate them for gcp too?

**Comment by brendanburns** [comment]
Probably worth duplicating them since we're cloning the code. It will help
prevent regressions.

The only reason that they're only azure is because most of the code was
shared.

**Comment by mansona** [comment]
I have added the tests for GCP now too 👍  

Would you mind approving the workflows on this? I had a strange test failure on my local machine that I can't explain and I want to know if it's something in my environment or if it's something that I've broken 🙈

**Comment by brendandburns** [comment]
Looks like ci/cd is failing....

**Comment by mansona** [comment]
that's actually perfect! it's failing with the same error that I got locally so I know it's not my environment 🎉 

I'll take a look and get this fixed in a bit 👍

**Comment by mansona** [comment]
I found the issue 🎉  there was a test that depended on the exact order and length of the authenticators in config instead of searching for the right one. 

I fixed that: https://github.com/kubernetes-client/javascript/pull/702/files#diff-f7d16ccc3d41b45b1511b3e65724c67009d49174a7a290c4034487e89e13141dL1001-R752

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
