### PR TITLE
Use the public npm registry

### LINKED ISSUE #594: Documentation not available
When trying to generate the documentation as per https://github.com/kubernetes-client/javascript/blob/master/README.md#documentation, I get the following errors from `npm install` :
image

Deleting the lockfile allows me to go further with the installation, however I am later met with a number of typescript error preventing me from running  `npm run build` successfully.

In order to reproduce the problem:
Clone the repository
Run `npm install`

Expected result:
Being able to `npm run docs`

Actual result:
`npm install` failure(s)

### PR DESCRIPTION
**Pull request by dominykas**
Should fix #594

### CODE REVIEW

**Comment by dominykas** [comment]
I signed it

**Comment by drubin** [comment]
hi @dominykas welcome :) and thanks for jumping in and fixing this. 

As you can see this was added in https://github.com/kubernetes-client/javascript/pull/510 which both @brendandburns and I reviewed. I think this must have slipped through the cracks. We should add a CI check to ensure only the public registry is used but quick googling didn't show up any built in configs to ensure this.

Similar to https://docs.npmjs.com/cli/v6/configuring-npm/package-json#publishconfig but for pulling of NPM packages.

I am curious to know why these tests kept passing in CI though. 

/lgtm 
/assign @brendandburns

**Comment by dominykas** [comment]
> We should add a CI check to ensure only the public registry is used but quick googling didn't show up any built in configs to ensure this.

Indeed I'm not aware of a thing that can enforce this, short of writing your own lint tool... Which is why I created an RRFC in npm to cover this case: https://github.com/npm/rfcs/issues/340.

Maybe someone already has a linter for that 🤷‍♂️ It shouldn't be hard to create one.

**Comment by brendandburns** [comment]
Thanks for the PR, apologies for letting this slip in.

/lgtm
/approve

**Pull request merged**
