### PR TITLE
Add support for certificate based exec auth.

### PR DESCRIPTION
**Pull request by brendandburns**
Replaces #282 

@edvald please take a look and test if possible, I don't have a DO cluster to check on...

### CODE REVIEW

**Comment by drubin** [comment]
The code looks good from my side but I am little hesitant to add a `lgtm` label since it will get merged and I have no way of verifying it actually works.

We can, of course, merge this and then do updates/fixes in another PR?

Either way @brendandburns you need to rebase.

**Comment by edvald** [comment]
I'll give it a spin today 👍

**Comment by brendandburns** [comment]
Rebased. @edvald did you get a chance to verify this?

THanks!

**Comment by drubin** [comment]
@brendanburns I think we should merge this it might not be fully tested but it doesn't break any existing functionality and we can easily submit fixes if need be. (else we are going to have to rebase constantly as it touches a bunch of core files).

/lgtm

**Pull request merged**
