### PR TITLE
chore: add cjihrig to OWNERS

### PR DESCRIPTION
**Pull request by cjihrig**
As discussed with @brendanburns via email.

Should I make a similar PR to the release-v1.x branch?

### CODE REVIEW

**Comment by brendandburns** [comment]
/verify-owners
/lgtm
/approve

@cjihrig I believe that this file is sufficient to be able to merge PRs to all branches in the repo. Let's see if it works, and if not, we can add it to the other branch.

**Comment by brendandburns** [comment]
@cjihrig looks like you need to add yourself here:

https://github.com/kubernetes/org/blob/main/config/kubernetes-client/org.yaml#L16

Raise a PR, I will put my support on the PR. We may need to get @mstruebing to do the same.

Apologies for the bureacracy.

**Comment by cjihrig** [comment]
No worries. I've opened https://github.com/kubernetes/org/issues/5295 and added you and @mstruebing (I hope that is OK. If not, it's totally fine.) as sponsors.

**Comment by mstruebing** [comment]
I've put in my +1 for you, we should probably wait until it's accepted before merging this PR here.

**Comment by cjihrig** [comment]
Thank you @mstruebing

**Comment by cjihrig** [comment]
Not sure if this will work yet, but...

/verify-owners

**Pull request merged**
