### PR TITLE
Update library to 1.9.x

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by hausdorff** [comment]
Any chance we could also apply the trivial changes I suggest in #13 to fix `--strict` incompatibility while we're at it? It should be 2 lines in `package.json`.

**Comment by brendandburns** [comment]
@hausdorff Does that look right?

Thanks
--brendan

**Comment by hausdorff** [comment]
@brendandburns Unless I'm missing something, I think it should be prefaced by a `dist/`, _e.g._, `"dist/index.js"`:

So, altogether:

```patch
@@ -10,7 +10,8 @@
     "*.ts",
     "*.js"
   ],
-  "main": "index.js",
+  "main": "dist/index.js",
+  "types": "dist/index.d.ts",
   "scripts": {
     "clean": "rm -Rf node_modules/ dist/",
     "build": "tsc",
```

**Comment by brendandburns** [comment]
Ok, I fixed it. There were some problems with the `package.json` and building the npm also, this all seems to work correctly now...

**Pull request merged**
