### PR TITLE
Add type restriction.

### LINKED ISSUE #864: Compilation breaks on Typescript 4.8.2, Ubuntu 20.04
When running tsc, it breaks with the following errors:
```
root@ec42f57e3eda:/mirrord/vscode-ext# tsc
node_modules/@kubernetes/client-node/dist/informer.d.ts:19:41 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

19     on(verb: string, fn: ObjectCallback<T>): void;
                                           ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:18:27
    18 export interface Informer<T> {
                                 ~
    This type parameter might need an `extends KubernetesObject` constraint.

node_modules/@kubernetes/client-node/dist/informer.d.ts:20:42 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

20     off(verb: string, fn: ObjectCallback<T>): void;
                                            ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:18:27
    18 export interface Informer<T> {
                                 ~
    This type parameter might need an `extends KubernetesObject` constraint.

node_modules/@kubernetes/client-node/dist/informer.d.ts:24:106 - error TS2344: Type 'T' does not satisfy the constraint 'KubernetesObject'.

24 export declare function makeInformer<T>(kubeconfig: KubeConfig, path: string, listPromiseFn: ListPromise<T>, labelSelector?: string): Informer<T>;
                                                                                                            ~

  node_modules/@kubernetes/client-node/dist/informer.d.ts:24:38
    24 export declare function makeInformer<T>(kubeconfig: KubeConfig, path: string, listPromiseFn: ListPromise<T>, labelSelector?: string): Informer<T>;
                                            ~
    This type parameter might need an `extends KubernetesObject` constraint.


Found 3 errors in the same file, starting at: node_modules/@kubernetes/client-node/dist/informer.d.ts:19 
```

** Client Version **
0.16.3

** Server Version **
N/A

**To Reproduce**
Run tsc on Ubuntu 20.04 with TypeScript 4.8.2

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - NodeJS Version 12.22.9
 
**Additional context**

You can view the error in a wider context in our [CI logs](https://github.com/metalbear-co/mirrord/runs/8057801870?check_suite_focus=true).

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #864

### CODE REVIEW

**Comment by JarnoRFB** [comment]
I believe `makeInformer` would also need the type constraint. Only when I add this locally in the `.d.ts` file the build in the [minimal example](https://github.com/JarnoRFB/kube-typerror) works again.

**Comment by brendandburns** [comment]
Yes you are correct, that change was in my client but I forgot to commit it. It is added now.

**Comment by brendandburns** [comment]
Self-merge since this is needed to fix a package that is breaking people.

**Comment by maddie-j** [comment]
Hi there! It seems the build failed for this change. Any chance it could be re-run? I'm assuming this will fix the `Could not find a declaration file for module 'request'/'ws'/'js-yaml'.` issue in 0.17.1?

**Comment by bencooper222** [comment]
Want to bump the previous comment - this fix is important but hasn't been released. Can you release it please?

**Pull request merged**
