### PR TITLE
Update README with build status and client status.

### LINKED ISSUE #47: Promote Javascript Client to Beta
This is an umbrella issue for remaining tasks to promote javascript client to beta.

@brendandburns would you add remaining tasks here and let me know how can I help?

### PR DESCRIPTION
**Pull request by brendandburns**
@mbohlool @flyboarder 

Closes #47

### CODE REVIEW

**Comment by flyboarder** [comment]
lgtm

**Comment by brendandburns** [comment]
@flyboarder can you try sending '/lgtm'

We recently activated some automation and that should apply the correct 'lgtm' label that will get this merged...

Thanks!

**Comment by flyboarder** [comment]
@brendandburns I am not cool enough for the k8s-ci-robot 😎

**Comment by brendandburns** [comment]
*sigh* I will invite you as a contributor...

**Pull request merged**
