### PR TITLE
chore: add kubectl equivalent examples

### PR DESCRIPTION
**Pull request by Ananya2001-an**
Related to #1253 
Created a `kubectl/equivalents` folder inside examples. Each file corresponds to the relevant kubectl command making it easier for users to understand the usage of the client. Makes it more readable and maintainable.

Current files added:
- Create namespace
- Create Namespace from yaml
- Create Namespaced pod
- List namespaces
- List Pods
- Create Resource quotas
- List all Resource quotas

... more to be added

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for this PR! I think it would be even better to introduce a `kubectl.js` as part of this library, so that people can simply call the `kubectl` equivalents.

It would be similar to https://github.com/kubernetes-client/java/tree/master/extended/src/main/java/io/kubernetes/client/extended/kubectl

**Comment by Ananya2001-an** [comment]
> Thanks for this PR! I think it would be even better to introduce a `kubectl.js` as part of this library, so that people can simply call the `kubectl` equivalents.

Yeah that sounds good! I will work on it. I think we can even add some tests for the same with jest, wdyt? But I would work on it in a separate PR to keep things simple for now :)

**Comment by Ananya2001-an** [comment]
Hey @brendandburns I created a `Kubectl.ts` file taking reference from the java client. Though, I am not very sure about how to create the generic execution calls for each function. Would like some help with that :) I have pushed the changes for your convenience.

**Comment by brendandburns** [comment]
Yes, you're right, there's no good equivalent of the generic client in Java. We should add that :)

If that's too much work, feel free to revert this PR just to the examples and we can merge those and work on the generic `kubectl` implementation some other time.

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Comment by Ananya2001-an** [comment]
Hey @brendandburns I would love to be a member of the kubernetes-client org and I was wondering how to proceed with it...like how one can apply for it? I know that one has to do some significant contribution work and I am willing to put that effort ;)

**Pull request merged**
