### PR TITLE
cpFromPod: close writerStream synchronously

### PR DESCRIPTION
**Pull request by fpm-peter**
This replicates https://github.com/kubernetes-client/javascript/pull/880 since https://github.com/kubernetes-client/javascript/pull/943 didn't solve the issue.

### CODE REVIEW

**Comment by fpm-peter** [comment]
/hold
there is another problem. The promise doesn't resolve correctly. Will update once I've had more time to investigate

**Comment by brendandburns** [comment]
Looks like CI/CD tests are failing.

**Comment by fpm-peter** [comment]
I can see why the last person didn't finish the PR. With the fake websocket never actually connecting to anything, the promise cannot resolve. Just comparing the called command with the expected called command proves nothing besides that exec is working as intended which is already validated in the exec_test. The exec-websocket-return is ignored in cpFromPod since this also proves nothing but that a connection got established - which is the problem of the bug in the first place.
I didn't find anything in other tests but is there an established way to test with an actual pod?

**Comment by brendandburns** [comment]
@fpm-peter unfortunately we don't have e2e tests with a real kubernetes cluster. You could add them, similar to the ones in the Java client here: https://github.com/kubernetes-client/java/blob/master/.github/workflows/maven.yml#L67

But that is a pretty big change to force you to do to merge this PR.

Perhaps the right answer is to remove this test if it isn't validating anything?

**Pull request closed without merging**
