### PR TITLE
Remove unused package

### PR DESCRIPTION
**Pull request by Leo7654**

### CODE REVIEW

**Comment by brendandburns** [comment]
@Leo7654 this looks good to me, but unfortunately even for a PR this small we need a signed CLA.

Thanks!

**Comment by Leo7654** [comment]
I signed it

**Comment by brendandburns** [comment]
Hrm, somehow it's not registering. Do you have the same email on your github account as you registered?

**Comment by Leo7654** [comment]
I signed it

**Comment by Leo7654** [comment]
I signed it

**Comment by drubin** [comment]
Hi @Leo7654 it doesn't seem to be registering. I think if you try step 3. in this doc it might help https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Leo7654** [comment]
@drubin @brendanburns Thanks! It seems to work!

**Comment by drubin** [comment]
@Leo7654 it's a pleasure! Thanks for your first contribution!

**Pull request merged**
