### PR TITLE
Add: deleteCollectionNamespacedCustomObject to support labelSelector

### PR DESCRIPTION
**Pull request by ArpanSolanki29**
Add support for labelSelector for deleteCollectionNamespacedCustomObject. 
This pr is regarding the issue: #1778

Note: Support for fieldSelector can be added once the [PR](https://github.com/kubernetes-client/gen/pull/272) is approved and merged

### CODE REVIEW

**Comment by brendandburns** [comment]
@ArpanSolanki29 can you try running this github action locally and attach a pointer to the logs/run.

Unfortunately, it's hard to test that changes to a github action actually work before running them.

**Comment by brendandburns** [comment]
For reference, this is adding in this commit:
https://github.com/kubernetes-client/gen/commit/a608a9dca32ca4792fe81822d61a7c8de3d0156b

**Review by anandfresh — APPROVED** [review]

**Comment by ArpanSolanki29** [comment]
Hi @brendandburns, thank you for reviewing the PR!

I've run the generate GitHub action locally, and here are the logs: [GitHub Action Logs](https://github.com/ArpanSolanki29/javascript/actions/runs/11529985582/job/32099012265).

The action confirmed that labelSelector is now accepted as a valid parameter. You can see the updated code section reflecting this: [Code Diff Link](https://github.com/ArpanSolanki29/javascript/pull/2/files#diff-b67df2564e59e85ac865fea18e8df6de8397336dabb87990499dc66592aee9dcR558).

Please let me know if there’s anything more needed—happy to help!

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for verifying!

**Comment by mstruebing** [comment]
I've removed the `do not merge` label as the PR in `kubernetes-client/gen` is already merged.

**Pull request merged**
