### PR TITLE
feat: custom path for service account token (supporting TokenVolume projection)

### LINKED ISSUE #1528: How to use this client with TokenVolume Projection
Hey,
I tried looking at the code but I couldn't figure how to do it. I am trying to use the more secure TokenVolume Projection to load short lived token instead of the long lived one, but I can't figure how to do it.

Can you please help me out with some examples?

### PR DESCRIPTION
**Pull request by omerlh**
fix #1528

I am not sure about the CA - I need to see if it will be there if using the projected volume 🤔

### CODE REVIEW

**Comment by omerlh** [comment]
While investigating the issue with CA and token projection I found this issue kubernetes/kubernetes#53315, I asked for help on Kubernetes slack

**Comment by omerlh** [comment]
When using TokenProjection need also to mount the custom config map `kube-root-ca.crt` with the API server CA certificate so I add the option to specify path to the CA as well

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks for the PR!

Once this merges, can you cherrypick it into the `release-1.x` branch also?

**Comment by brendandburns** [comment]
ugh, looks like we need to fix the linter somewhat.

**Comment by omerlh** [comment]
Yeah, the linter error does not look related to my changes so I am not sure what to do, I think need to upgrade linter rules maybe?

**Comment by mstruebing** [comment]
Hey @omerlh I think the linter errors are not really failing, prettier is what is failing.
If I run `npm run format` and after that `npm run lint` I get an exit code of zero.
Without running `npm run format` it's 1. So if you run `npm run format` and commit and push these changes the linter should be satisfied.

I'm not sure about our linter setup though, we should probably switch to eslint or something else which is supported as tslint is deprecated since quite a while (2019)

**Comment by omerlh** [comment]
Sure, I just did - let's see if this will help!

**Comment by mstruebing** [comment]
/lgtm
/approve

Thank you for your contribution 🎉

**Pull request merged**
